postgres:
  image: postgres:12
  ports:
    - '5432:5432'
  environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=pass
    - POSTGRES_DB=database
cassandra:
  build: docker/cassandra
  ports:
    - "9042:9042/tcp"